version: '3.8'

services:
  master:
    hostname: cluster-master
    build:
      context: .
      target: node
    image: mysql-master
    tty: true
    volumes:
      - ./config/config.ini:/var/lib/mysql-cluster/config.ini
    command: bash -c 'until [ 1 -gt 2 ];do echo Sleeping; sleep 10; done'
  
  node_one:
    hostname: node_one
    build:
      context: .
      target: node
    image: mysql-node
    tty: true

  node_two:
    hostname: node_two
    build:
      context: .
      target: node
    image: mysql-node
    tty: true
