version: '3.8'

services:
  master:
    hostname: cluster-master
    build:
      context: .
      target: node
    image: mysql-master
    environment:
      HOSTNAMES: node_one node_two
    volumes:
      - ./config/config.ini:/var/lib/mysql-cluster/config.ini
    command: bash -c 'tail -f /var/lib/mysql-cluster/ndb_1_cluster.log'
  
  node_one:
    hostname: node_one
    build:
      context: .
      target: node
    image: mysql-node
    tty: true

  node_two:
    hostname: node_two
    build:
      context: .
      target: node
    image: mysql-node
    tty: true
